theme = "catppuccin_mocha"

[editor]
true-color = true
auto-format = true
indent-heuristic = "hybrid"
line-number = "relative"
cursorline = true
cursorcolumn = false
gutters = ["diagnostics", "line-numbers", "spacer"]
auto-pairs = true
auto-completion = true
auto-info = true
soft-wrap.enable = true
indent-guides.render = true
indent-guides.character = "│"

[editor.smart-tab]
enable = true
