" Auto close brackets and quotes
inoremap ( ()<Left>
inoremap [ []<Left>
inoremap { {}<Left>
inoremap ' ''<Left>
inoremap " ""<Left>

syntax on

" Enable smart indentation
filetype plugin indent on
set smartindent
set autoindent

" Use spaces instead of tabs
set expandtab

" Number of spaces for each indentation
set tabstop=4
set shiftwidth=4
set softtabstop=4

" Show line numbers (optional)
set number

" Enable backspace over everything in insert mode
set backspace=indent,eol,start
