 1 " Auto close brackets and quotes
  2 inoremap ( ()<Left>
  3 inoremap [ []<Left>
  4 inoremap { {}<Left>
  5 inoremap ' ''<Left>
  6 inoremap " ""<Left>
  7 syntax on
  8 " Enable smart indentation
  9 filetype plugin indent on
 10 set smartindent
 11 set autoindent
 12 
 13 " Use spaces instead of tabs
 14 set expandtab
 15 
 16 " Number of spaces for each indentation
 17 set tabstop=4       " How many spaces a <Tab> looks like
 18 set shiftwidth=4    " Number of spaces to use for autoindent
 19 set softtabstop=4   " Number of spaces inserted/deleted with <Tab>/<BS>
 20 
 21 " Show line numbers (optional)
 22 set number
 23 
 24 " Enable backspace over everything in insert mode
 25 set backspace=indent,eol,start
